# Generated by Django 3.1.4 on 2020-12-04 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doubt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('teacher', models.CharField(blank=True, max_length=20)),
                ('question', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True)),
                ('language', models.CharField(max_length=10)),
                ('is_answered', models.BooleanField(default=False)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
            ],
        ),
    ]
